# Day 29: Build Operation Lifeline - A Supply Chain Crisis Lab
# ABTalks 60 Days Claude Challenge | By Kanchan

import streamlit as st
import time
import random
import pandas as pd

st.set_page_config(page_title="Operation Lifeline", page_icon="🚚", layout="wide")

st.title("🚚 Day 29: Operation Lifeline - A Supply Chain Crisis Lab")
st.subheader("ABTalks x Claude AI Challenge | Supply Chain Crisis Simulator")
st.markdown("---")

# Sidebar - Crisis Controls
st.sidebar.header("⚠️ Crisis Control Tower")
crisis_type = st.sidebar.selectbox("Select Crisis Scenario", 
    ["Flood in Lucknow - Medicine Block", "Oxygen Cylinder Shortage", "Cold Chain Failure", "Fuel Strike - Transport Halt", "Hospital Demand Surge"]
)
location = st.sidebar.selectbox("Impact Location", ["Lucknow", "Kanpur", "Itaunja", "Barabanki", "Ayodhya"])
severity = st.sidebar.slider("Severity Level", 1, 10, 7)
st.sidebar.metric("Supply at Risk", f"{severity * 12}%", f"+{severity*2}% last hour")

if st.sidebar.button("🚨 Trigger Crisis Simulation"):
    st.session_state.trigger = True
else:
    if 'trigger' not in st.session_state:
        st.session_state.trigger = False

# Main Dashboard
col1, col2, col3, col4 = st.columns(4)
col1.metric("🚑 Hospitals Affected", f"{severity * 3}", f"{severity} critical")
col2.metric("💊 Stock Left", f"{100 - severity*9} units", f"-{severity*5} today")
col3.metric("🚚 Trucks Delayed", f"{severity * 2}", "Needs reroute")
col4.metric("⏱️ ETA to Resolve", f"{severity * 2 + 2} hours", "AI Optimized")

st.markdown("### 📦 Live Inventory Dashboard")
data = {
    "Item": ["Oxygen Cylinders", "Paracetamol", "IV Fluids", "Blood Bags", "Surgical Kits"],
    "In Stock": [120 - severity*10, 500 - severity*30, 300 - severity*20, 80 - severity*5, 150 - severity*12],
    "Demand Today": [100 + severity*10, 400 + severity*20, 250 + severity*15, 60 + severity*8, 100 + severity*10],
    "Status": ["Critical" if (120-severity*10) < 50 else "Low" for _ in range(5)]
}
df = pd.DataFrame(data)
st.dataframe(df, use_container_width=True)

# Simulation Logic
if st.session_state.trigger:
    st.markdown("---")
    st.markdown(f"### 🎯 Crisis Active: **{crisis_type}** in **{location}**")
    
    with st.status("🤖 Claude AI running Operation Lifeline Protocol...", expanded=True) as status:
        st.write(f"📡 Scanning supply routes to {location}...")
        time.sleep(1.2)
        st.write(f"🔍 Identifying alternate suppliers for {crisis_type}...")
        time.sleep(1.2)
        st.write("🧠 AI generating crisis response plan...")
        time.sleep(1.5)
        status.update(label="✅ Lifeline Plan Ready!", state="complete", expanded=False)

    tab1, tab2, tab3 = st.tabs(["🚀 AI Solution", "🗺️ Reroute Plan", "📢 Action Log"])

    with tab1:
        st.success(f"**Solution Generated by Claude AI for Severity {severity}/10**")
        if "Flood" in crisis_type:
            st.write("**Plan:** Use boats + drone delivery for Itaunja-Lucknow route. Shift stock from Kanpur warehouse (45km extra but safe).")
        elif "Oxygen" in crisis_type:
            st.write("**Plan:** Priority dispatch from Barabanki plant. Request 50 cylinders from private vendors. Implement rationing for non-critical cases.")
        elif "Cold Chain" in crisis_type:
            st.write("**Plan:** Activate backup cold storage in Lucknow SGPGI. Use ice-lined boxes for 12-hour transport window.")
        elif "Fuel" in crisis_type:
            st.write("**Plan:** Use CNG trucks, pool delivery for 3 hospitals in one route. Contact EV delivery partners.")
        else:
            st.write("**Plan:** Open emergency ward in Itaunja CHC, divert 30% patients from Lucknow KGMU. Deploy mobile medical unit.")
        st.metric("Estimated Lives Saved", f"{severity * 8 + random.randint(5,15)}")
    
    with tab2:
        st.write(f"**Original Route:** Central Depot -> {location} (Blocked)")
        st.write(f"**New Route:** Central Depot -> Kanpur Bypass -> Safe Corridor -> {location}")
        st.progress(75)
        st.write("**ETA Improved:** 2.5 hours faster than original")

    with tab3:
        st.code(f"""
        [09:01] Crisis Detected: {crisis_type}
        [09:02] Alert Sent to 12 Hospitals in {location}
        [09:05] Claude AI Activated
        [09:07] Alternate Supplier Found: MedPlus Kanpur
        [09:10] Reroute Confirmed - 3 Trucks Dispatched
        [09:15] Operation Lifeline - SUCCESS
        """)
    
    st.balloons()
    st.info("💡 This is a simulation for healthcare supply chain resilience | Day 29 Completed")

else:
    st.info("👈 Sidebar se Crisis Scenario select karo aur 'Trigger Crisis Simulation' dabao simulation dekhne ke liye!")

st.markdown("---")
st.caption("Day 29/60 | #ABTalks #SupplyChainAI #OperationLifeline | github.com/km0438591-arch/60-days-claude-ai-challenge")
